  version: '3'
  services:
    backend:
      build:
        context: ./backend
      ports:
        - "8000:8000"
      networks:
        - docker-network

    frontend:
      build:
        context: ./frontend
      ports:
        - "5173:80"

    mongo:
      image: mongo:latest
      ports:
        - "27017:27017"
      networks:
        - docker-network

  networks:
    docker-network:
      driver: bridge
