---
- name: Deploy Todo Application
  hosts: all
  become: yes
  vars:
    docker_compose_version: "1.29.2"
    backend_image: "shageeth/to-do-application-backend:latest"
    frontend_image: "shageeth/to-do-application-frontend:latest"
    app_dir: "/opt/todo-app"
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update yum cache for RedHat family
      yum:
        update_cache: yes
        use_backend: yum
      when: ansible_os_family == "RedHat"
      
    - name: Update yum cache for Amazon Linux
      command: yum makecache
      changed_when: false
      when: ansible_distribution == "Amazon"

    - name: Install required packages (RedHat/Amazon Linux)
      yum:
        name:
          - docker
          - python3-pip
          - git
        state: present
      when: ansible_os_family == "RedHat" or ansible_distribution == "Amazon"
      
    - name: Install required packages (Debian)
      apt:
        name:
          - docker.io
          - python3-pip
          - git
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Create docker-compose.yml
      template:
        src: ../templates/docker-compose.yml.j2
        dest: "{{ app_dir }}/docker-compose.yml"
      
    - name: Login to Docker Hub
      shell: "docker login -u {{ docker_hub_username }} -p {{ docker_hub_password }}"
      no_log: true
      vars:
        docker_hub_username: "{{ lookup('env', 'DOCKER_HUB_USERNAME') }}"
        docker_hub_password: "{{ lookup('env', 'DOCKER_HUB_PASSWORD') }}"
      
    - name: Pull Docker images
      shell: "docker pull {{ item }}"
      loop:
        - "{{ backend_image }}"
        - "{{ frontend_image }}"
        - "mongo:latest"

    - name: Deploy with Docker Compose
      shell: "cd {{ app_dir }} && docker-compose down && docker-compose up -d"
      
    - name: Wait for services to be up
      wait_for:
        host: localhost
        port: 80
        timeout: 300
        
    - name: Clean up old Docker images
      shell: "docker image prune -af"